In [ ]:
import pandas as pd
import numpy as np

In [3]:
import requests

In [5]:
df = requests.get('https://www.omdbapi.com/?i=tt3896198&apikey=e6eb8d27&t=dhurandhar%20the%20revenge')

##### <Response [200]> means that the thing we are doing is done , similarly response 500 means that the thing which we are searching is not available or might be server down

In [6]:
df.json()

{'Title': 'Dhurandhar The Revenge',
 'Year': '2026',
 'Rated': 'N/A',
 'Released': '19 Mar 2026',
 'Runtime': '230 min',
 'Genre': 'Action, Crime, Thriller',
 'Director': 'Aditya Dhar',
 'Writer': 'Aditya Dhar',
 'Actors': 'Ranveer Singh, Akshaye Khanna, Sanjay Dutt',
 'Plot': 'Jaskirat Singh Rangi descends deeper into his alias as Hamza Ali Mazari, rising through Karachi\'s criminal hierarchy to claim the feared title "Sher-e-Baloch" while balancing loyalty, betrayal, and survival in a ruthless underworld.',
 'Language': 'Hindi',
 'Country': 'India',
 'Awards': 'N/A',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNzdkNjAxNWMtNWY3My00NTI1LTg2YWQtOGI3MDA0NzdhMjEyXkEyXkFqcGc@._V1_QL75_UY562_CR24,0,380,562_.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.5/10'}],
 'Metascore': 'N/A',
 'imdbRating': '8.5',
 'imdbVotes': '45,701',
 'imdbID': 'tt39139925',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$27,415,192',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [ ]:
df2 = pd.DataFrame(df.json())

In [ ]:
df2[['Title','Year','Actors','imdbRating']]
# when we select multiple columns then we use double list and not single list when we use only single columns then we use single list or we can also use double list

,Title,Year,Actors,imdbRating
0,Dhurandhar The Revenge,2026,"Ranveer Singh, Akshaye Khanna, Sanjay Dutt",8.5

# Using rapid API KEY

In [ ]:
import pandas as pd
import numpy as np 
import requests

In [50]:
url = "https://imdb232.p.rapidapi.com/api/actors/get-related-news"

headers = {
    "X-Rapidapi-Key" : "534ef14325msh3799c8c7f579a14p16be02jsn8dc2f5b85de3",
    "X-Rapidapi-Host" : "imdb232.p.rapidapi.com"
}

# querystring = {
#     "limit" : "20",
#     "page" : "10",
#     "quality" : "all",
#     "genre" : "all"
# }

# response = requests.get(url,headers=headers,params=querystring)
response = requests.get(url,headers=headers)

In [55]:
data = response.json()
print(data)

{'errors': [{'message': 'undefined is not a valid ID for type with prefix nm', 'path': ['name'], 'extensions': {'code': 'BAD_USER_INPUT', 'errorType': 'CLIENT', 'isRetryable': False, 'path': ['name'], 'symbol': 'id'}}], 'data': {'name': None}}

In [54]:
print(response.status_code)

200

In [53]:
df3 = pd.json_normalize(data)
df3.head()

                                              errors data.name
0  [{'message': 'undefined is not a valid ID for ...      None

##### URL = Protocol + Host + Path + Query Parameters

##### Example:
##### https://movie-database-api1.p.rapidapi.com/list_movies.json?limit=20&page=1

##### Protocol -> https
##### Host     -> movie-database-api1.p.rapidapi.com
##### Path     -> /list_movies.json
##### Query    -> limit=20&page=1

##### Headers are NOT part of the URL.
##### Example headers:
##### X-RapidAPI-Key : Your_API_Key
##### X-RapidAPI-Host: movie-database-api1.p.rapidapi.com

##### requests.get() uses:
##### requests.get(url, headers=headers, params=params)