In [56]:
import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [57]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived','Pclass'])

In [58]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [59]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [60]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [62]:
X_train.sample(10)

     Pclass   Age    Fare
55        1   NaN  35.500
607       1  27.0  30.500
714       2  52.0  13.000
112       3  22.0   8.050
668       3  43.0   8.050
150       2  51.0  12.525
273       1  37.0  29.700
168       1   NaN  25.925
405       2  34.0  21.000
120       2  21.0  73.500

In [ ]:
knn = KNNImputer(n_neighbors=3,weights='distance',add_indicator=True)
# in KNNimputer there are two most important parameter first is n_neighbour, which you can set to any value and the second is weights which is of two type uniform and distance , in uniform all the nearest neighbout get equal importance while in distance the age is more closer get more importance 
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [64]:
X_train_trf = pd.DataFrame(X_train_trf,columns=X_train.columns)

In [65]:
X_train_trf.sample(10)

     Pclass        Age     Fare
411     3.0  35.000000   7.8958
21      2.0  48.000000  13.0000
558     2.0  34.000000  21.0000
311     3.0  32.000000   7.7500
286     3.0  19.415808   7.7292
331     3.0  14.000000   7.8542
665     2.0  19.000000  10.5000
577     2.0  28.000000  10.5000
166     2.0  27.000000  13.0000
160     3.0  22.000000   9.3500

In [66]:
X_train_trf.isnull().mean()*100

Pclass    0.0
Age       0.0
Fare      0.0
dtype: float64

In [67]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

0.7094972067039106

In [68]:
# comparison with simple imputer 

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_pred2,y_test)

0.6927374301675978