In [79]:
import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [80]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived','Pclass'])

In [81]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [82]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [83]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [84]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [85]:
X_train.sample(10)

     Pclass   Age     Fare
825       3   NaN   6.9500
783       3   NaN  23.4500
221       2  27.0  13.0000
81        3  29.0   9.5000
123       2  32.5  13.0000
39        3  14.0  11.2417
229       3   NaN  25.4667
401       3  26.0   8.0500
667       3   NaN   7.7750
574       3  16.0   8.0500

In [86]:
knn = KNNImputer(n_neighbors=3,weights='distance')
# in KNNimputer there are two most important parameter first is n_neighbour, which you can set to any value and the second is weights which is of two type uniform and distance , in uniform all the nearest neighbout get equal importance while in distance the age is more closer get more importance 
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [87]:
X_train_trf = pd.DataFrame(X_train_trf,columns=X_train.columns)

In [88]:
X_train_trf.sample(10)

     Pclass   Age    Fare
78      3.0  45.0   8.050
655     3.0  31.0  23.450
333     2.0  27.0  26.000
391     3.0   9.0  34.375
146     1.0  65.0  26.550
591     3.0   6.0  12.475
585     1.0  22.0  49.500
518     1.0  45.0  35.500
209     3.0  18.0  18.000
527     3.0  33.0  20.525

In [89]:
X_train_trf.isnull().mean()*100

Pclass    0.0
Age       0.0
Fare      0.0
dtype: float64

In [90]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

0.7094972067039106

In [91]:
# comparison with simple imputer 

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_pred2,y_test)

0.6927374301675978